### ISSUE TITLE
Received error during install and corkscrew explode output file only shows curly brackets'{}'

### ISSUE THREAD

**Issue by stariqali** [f5devcentral/f5-corkscrew#20]
Received this error during install
[ansible@centos config_split]$ sudo `npm install -g https://github.com/f5devcentral/f5-corkscrew.git`
npm WARN deprecated @types/deepmerge@2.2.0: This is a stub types definition. deepmerge provides its own type definitions, so you do not need this installed.

It appears that the package installed succesrfully, but only the curly bracket after I attempt to run "corkscrew explode <bigip.conf>"
[ansible@centos config_split]$ node --version
v10.19.0
[ansible@centos config_split]$ npm --version
6.13.4
[ansible@centos config_split]$ corkscrew --version
0.8.0
[ansible@centos config_split]$ corkscrew explode ./bigip.conf > newfile.json
[ansible@centos config_split]$ cat newfile.json
{}
[ansible@centos config_split]$ corkscrew explode ./bigip.conf >> newfile.json
[ansible@centos config_split]$ cat newfile.json

bigip.conf file has 1500 plus vips.

**Comment by DumpySquare** [comment]
@stariqali, any update on this?  is it working now?  can we close this issue?
