### ISSUE TITLE
[BUG] no cli parse output in my environment

### ISSUE THREAD

**Issue by 00mfg** [f5devcentral/f5-corkscrew#27]
<img width="545" alt="image" src="https://user-images.githubusercontent.com/34377061/233290627-b21ea8d8-7632-4fcf-887c-69332716cfce.png">
test corkscrew version 0.10.0 to latest 0.13.0 , use devCloud01_10.7.2020.conf as input ,but there is no output for parse result,
 could you pls advise if i miss something. or how can i get more debug log? thanks

<img width="1766" alt="image" src="https://user-images.githubusercontent.com/34377061/233291561-f34f880c-2abd-4996-8187-3c5a7e1c31b2.png">

**Comment by DumpySquare** [comment]
Hi @00mfg !  I never got any feedback on people using the CLI so i haven't been testing it through the updates.  

If this is something you really need, I can work on getting it working again.  Can you help me understand your use case and the details your looking for?

**Comment by 00mfg** [comment]
> Hi @00mfg ! I never got any feedback on people using the CLI so i haven't been testing it through the updates.
> 
> If this is something you really need, I can work on getting it working again. Can you help me understand your use case and the details your looking for?

hi @DumpySquare thx for reply. could you pls advise except CLI how to use this cooooool tools.  here is my use case, i 'd like to use tools like ntc-template to parse text config to json ，but as you may know just network device template there. so your tools seems meet my requirment, if i got json output then i can leverage it to do more automation。thanks

**Comment by 00mfg** [comment]
> Hi @00mfg ! I never got any feedback on people using the CLI so i haven't been testing it through the updates.
> 
> If this is something you really need, I can work on getting it working again. Can you help me understand your use case and the details your looking for?

hi @DumpySquare thx for reply. could you pls advise except CLI how to use this cooooool tools.  here is my use case, i 'd like to use tools like ntc-template to parse text config to json ，but as you may know just network device template there. so your tools seems meet my requirment, if i got json output then i can leverage it to do more automation。thanks

**Comment by DumpySquare** [comment]
completed in pending v1.1.0 release;
you probably need a newer version of node/npm, like v16/v8
check out the tests for latest usage.  will update documentation soon
tests/056_cli.tests.ts

**Comment by 00mfg** [comment]
cooooooool,thx @DumpySquare
