### ISSUE TITLE
[RFE] deeper parsing of key ltm objects

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/f5-corkscrew#30]
continue the deep parsing from gslb to the following key ltm elements

virtual servers
pools
nodes
monitors

Anything else?

**Comment by GlenWillms** [comment]
iRules: Name, Body
Virtual Server: Name, IP, Port, Port Type, iRules, ASM Policy, APM Policy, SNAT

**Comment by DumpySquare** [comment]
completed in pending v1.1.0 release
